### ISSUE TITLE
Pack & Push not working

### ISSUE THREAD

**Issue by tolgaonbay** [mckn/gulp-nuget#13]
Hi,

I'm trying to pack and push a package to a nuget server. Pack command creates the package but deletes the file before completion, so the push command cannot find the file specified. Is there any configuration that I am missing? Thanks

```
gulp.task('nuget-pack-n-push-website', function() {
    return gulp.src(config.release.website)
        .pipe(nuget.pack({
            nuget: nugetExecutable,
            version: version
        }))
        .pipe(nuget.push({
            nuget: nugetExecutable,
            source: 'http://example.com/nuget/nuget',
            apiKey: '00000000-0000-0000-0000-000000000000'
        }));
});

```

```
[15:19:21] MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Attempting to build package from 'Example.nuspec'.
Successfully created package './.gulp-nuget\Example.1.0.nupkg'.

c:\example\node_modules\gulp-nuget\lib\push.js:22
                        if(err) throw new gutil.PluginError('gulp-nuget', err);
                                ^
Error: Command failed: c:/Example/nuget/nuget.exe push ./.gulp-nuget\Example.1.0.nupkg -source http://example.com/nuget/nuget -apiKey 00000000-0000-0000-0000-000000000000 -noninteractive
Could not find a part of the path 'c:\Example\.gulp-nuget'.

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```

OS: Windows 7
gulp: 3.9.1
node: 4.1.2
npm: 3.7.5
gulp-nuget: 1.0.0

**Comment by mckn** [comment]
Hello,

Thanks for reporting this! It is a bug. I will fix this later today and push an update.

Best regards,
Marcus

**Comment by tolgaonbay** [comment]
Hi,

Any updates?

Best,
Tolga

**Comment by tgourley01** [comment]
updates?
