### ISSUE TITLE
Handling nuget push errors

### ISSUE THREAD

**Issue by ghost** [mckn/gulp-nuget#6]
If nuget push fails with an error, the following stack trace is shown and no error information is visible:

Error: no writecb in Transform class
    at afterTransform (_stream_transform.js:90:33)
    at TransformState.afterTransform (_stream_transform.js:74:12)
    at \node_modules\gulp-nuget\lib\push.js:38:3
    at \node_modules\gulp-nuget\lib\push-cmd.js:24:3
    at ChildProcess.exithandler (child_process.js:652:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

I assume this because push-cmd calls the callback twice in case of an error.

**Comment by mckn** [comment]
Should be resolved in new version 1.0.0
